name: SmartSearch Indexing

on:
  push:
    paths:
      - 'sourcecode/**'
    branches:
      - '*'

jobs:
  run-indexing:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -f http://localhost:9200/_cat/health" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
        env:
          discovery.type: single-node

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Elasticsearch to be ready
      run: |
        until curl -s http://localhost:9200; do echo Waiting for Elasticsearch...; sleep 5; done

    - name: Run indexing
      run: |
        python codebase_search.py --index ./sourcecode
