name: SmartSearch Indexing

on:
  push:
    paths:
      - 'sourcecode/**'
    branches:
      - '*'

jobs:
  run-indexing:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
        options: >-
          --health-cmd="curl -f http://localhost:9200/_cat/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK Resources
        run: |
          mkdir -p /home/runner/nltk_data
          python -c "import nltk; nltk.download('stopwords', download_dir='/home/runner/nltk_data')"

      - name: Wait for Elasticsearch DNS and Port
        run: |
          # Wait for 'elasticsearch' DNS
          for i in {1..10}; do
            if nslookup elasticsearch >/dev/null; then
              echo "DNS for 'elasticsearch' resolved"
              break
            fi
            echo "DNS not available yet, retrying..."
            sleep 5
          done

          # Then wait for port 9200 to respond
          for i in {1..10}; do
            if curl -s http://elasticsearch:9200 > /dev/null; then
              echo "Elasticsearch is up!"
              break
            fi
            echo "Waiting for Elasticsearch to respond on port 9200..."
            sleep 5
          done

      - name: Run indexing
        env:
          NLTK_DATA: /home/runner/nltk_data
        run: |
          python codebase_search.py --index ./sourcecode

      - name: Print Elasticsearch logs on failure
        if: failure()
        run: |
          echo "Elasticsearch container logs:"
          docker logs $(docker ps --filter "name=elasticsearch" -q)
